apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "nexusdesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  OPENROUTER_API_KEY: {{ .Values.secrets.openrouterApiKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
